### ISSUE TITLE
Add orientation change tracking

### ISSUE THREAD

**Issue by vpodk** [Datamart/Komito#26]
- [x] Implement orientation tracker functionality under `dom` namespace;
- [x] Add to default configuration as "trackOrientation" property;
- [x] Add to the list of non interaction events;
