### ISSUE TITLE
Add tracking pageviews with blocked ads

### ISSUE THREAD

**Issue by vpodk** [Datamart/Komito#27]
- [x] Implement adblock tracker functionality under `dom` namespace;
- [x] Add to default configuration as "trackAdblock" property;
- [x] Add to the list of non interaction events;

**Comment by vpodk** [comment]
Thanks to @ppokyd!
